class CreateRelatedMaterials < ActiveRecord::Migration
      extend Inkling::Util::MigrationHelpers
      
  def self.up
    create_table :related_materials do |t|
      t.integer :study_id
      t.text      :abstract_text
      t.text      :accessibility
      t.text      :addressee
      t.text      :addressee_copy
      t.text      :aggregation
      t.text      :alternative_title
      t.text      :audience
      t.text      :authorising_statute
      t.date      :auto_remove_date
      t.date      :beginning_date
      t.text      :bibliographic_citation
      t.text      :category
      t.text      :comment
      t.text      :conforms_to
      t.text      :contributor
      t.text      :copyright
      t.text      :coverage
      t.text      :coverage_temporal_date_capture_period_ends
      t.datetime  :creation_date
      t.text      :creator
      t.text      :current_location
      t.text      :custodian
      t.date      :cut_off_date
      t.text      :dpa_data_subject_access_exemption
      t.text      :data_protection_exempt_category
      t.date      :date_accepted
      t.date      :date_acquired
      t.date      :date_available
      t.date      :date_available_end
      t.text      :date_capture_period
      t.date      :date_closed
      t.date      :date_copyrighted
      t.date      :date_created
      t.date      :date_declared
      t.date      :date_issued
      t.date      :date_modified
      t.date      :date_next_version_due
      t.date      :date_of_last_review
      t.date      :date_submitted
      t.date      :date_valid
      t.date      :date_valid_end
      t.text      :dates_modified
      t.text      :deploy_language
      t.text      :descriptor
      t.text      :digital_signature
      t.text      :disclosability_to_dpa_data_subject
      t.text      :disposal
      t.text      :disposal_action
      t.text      :disposal_authorised_by
      t.text      :disposal_comment
      t.text      :disposal_conditions
      t.date      :disposal_date
      t.text      :disposal_export_destination
      t.text      :disposal_export_status
      t.text      :disposal_review
      t.text      :disposal_review_details
      t.text      :disposal_reviewer_details
      t.text      :disposal_schedule_id
      t.text      :disposal_time_period
      t.text      :eir_disclosability_indicator
      t.text      :eir_exemption
      t.text      :education_level
      t.date      :end_date
      t.date      :end_date_of_capture
      t.text      :extend
      t.text      :external_id
      t.text      :foi_disclosability_indicator
      t.text      :foi_exemption
      t.date      :foi_release_date
      t.text      :foi_release_details
      t.text      :file_plan_id
      t.text      :format
      t.text      :group_access
      t.text      :has_format
      t.text      :has_part
      t.text      :has_version
      t.string    :home_location
      t.text      :identifier
      t.text      :identifier_case_id
      t.text      :individual_user_access_list
      t.text      :is_defined_by
      t.text      :is_format_of
      t.text      :is_part_of
      t.text      :is_referenced_by
      t.text      :is_replaced_by
      t.text      :is_required_by
      t.text      :is_version_of
      t.text      :keyword
      t.text      :label
      t.text      :language
      t.text      :last_fio_disclosability_review
      t.text      :location
      t.text      :mandate
      t.text      :mediator
      t.text      :medium
      t.text      :notes
      t.text      :original_format
      t.text      :personal_data_acquisition_purpose
      t.integer   :position
      t.text      :postcode
      t.text      :preservation
      t.text      :previous_protective_marketing
      t.text      :process_identifier
      t.text      :programme
      t.text      :project
      t.text      :protective_marketing
      t.date      :protective_marketing_change_date
      t.date      :protective_marketing_expiry_date
      t.text      :provides_definition_of
      t.text      :publisher
      t.text      :reason_for_redaction
      t.text      :redaction
      t.text      :relation
      t.text      :replaces
      t.text      :requires
      t.text      :resource_date
      t.text      :resource_references
      t.text      :resource_type
      t.text      :rights
      t.text      :schedule_catalog_id
      t.datetime  :schedule_date
      t.text      :schedule_email_text
      t.text      :sequence_num
      t.text      :source
      t.text      :spatial_location
      t.text      :spatiality
      t.date      :start_date_of_capture
      t.text      :status
      t.text      :status_of_start_date_of_capture
      t.string    :study_id
      t.boolean   :sub_resource
      t.text      :subject
      t.text      :subject_person
      t.text      :system_id
      t.text      :table_of_contents
      t.text      :temporal
      t.text      :updating_frequency
      t.text      :uri        

      t.timestamps
    end
    
    add_foreign_key(:related_materials, :study_id, :studies)
    
  end

  def self.down
      drop_table :related_materials
  end
end
